fix(deps): update dependency org.openapitools:openapi-generator to v7.18.0 (#650)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
|
[org.openapitools:openapi-generator](https://redirect.github.com/openapitools/openapi-generator)
| `7.17.0` -> `7.18.0` |
![age](https://developer.mend.io/api/mc/badges/age/maven/org.openapitools:openapi-generator/7.18.0?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.openapitools:openapi-generator/7.17.0/7.18.0?slim=true)
|

---

### Release Notes

<details>
<summary>openapitools/openapi-generator
(org.openapitools:openapi-generator)</summary>

###
[`v7.18.0`](https://redirect.github.com/OpenAPITools/openapi-generator/releases/tag/v7.18.0):
released

[Compare
Source](https://redirect.github.com/openapitools/openapi-generator/compare/v7.17.0...v7.18.0)

v7.18.0 stable release comes with 130+ enhancements, bug fixes. Once
again thanks for all the contributions from the community.

Below are the highlights of the changes. For a full list of changes,
please refer to the ["Pull
Request"](https://redirect.github.com/OpenAPITools/openapi-generator/pulls?q=is%3Amerged+is%3Apr+milestone%3A7.18.0+)
tab.

#### General

- feat: prevent variable resolution when prefixed with $ in server URL
templates
[#&#8203;22550](https://redirect.github.com/openapitools/openapi-generator/issues/22550)
- Fix siblings of $ref using allOf in openapi normalizer
[#&#8203;22364](https://redirect.github.com/openapitools/openapi-generator/issues/22364)

#### C++

- fix(cpp-qt): Fix enum query parameter serialization for both inline
and referenced enums
[#&#8203;22559](https://redirect.github.com/openapitools/openapi-generator/issues/22559)
- \[cpp-rest] Fixes segfault for nullable strings
[#&#8203;22405](https://redirect.github.com/openapitools/openapi-generator/issues/22405)
- Add Basic and Bearer Authorization to the CPP Pistache generator
[#&#8203;22337](https://redirect.github.com/openapitools/openapi-generator/issues/22337)
- Fixes oatpp generator to expose network server on 0.0.0.0 instead of
localhost
[#&#8203;22330](https://redirect.github.com/openapitools/openapi-generator/issues/22330)
- \[cpp-rest] Fixing Incorrect Header Name Used
[#&#8203;22298](https://redirect.github.com/openapitools/openapi-generator/issues/22298)

#### C\#

- \[csharp] Patch dependencies with vulnerabilities
[#&#8203;22262](https://redirect.github.com/openapitools/openapi-generator/issues/22262)

#### Crystal

- fix(generator): fix java.lang.NullPointerException in constructing
example code
[#&#8203;22545](https://redirect.github.com/openapitools/openapi-generator/issues/22545)
- \[crystal] fix Model#to\_h method
[#&#8203;22508](https://redirect.github.com/openapitools/openapi-generator/issues/22508)
- \[crystal] Add option to set params\_encoder
[#&#8203;22484](https://redirect.github.com/openapitools/openapi-generator/issues/22484)
- \[crystal-lang] Various fixes for Crystal client
[#&#8203;22465](https://redirect.github.com/openapitools/openapi-generator/issues/22465)

#### Go

- \[GO] Generate imports for UnmarshalJSON func only when it's present
[#&#8203;22524](https://redirect.github.com/openapitools/openapi-generator/issues/22524)
- fix: missing imports for array of files and date-time parameters
[#&#8203;22390](https://redirect.github.com/openapitools/openapi-generator/issues/22390)

#### Java

- \[BUG]\[JAVA]\[Spring] fix Lombok
[@&#8203;Getter](https://redirect.github.com/Getter) disables validation
[#&#8203;22544](https://redirect.github.com/openapitools/openapi-generator/issues/22544)
- Fix Spring Framework 7 compatibility in jvm-spring-restclient and
jvm-spring-webclient
[#&#8203;22467](https://redirect.github.com/openapitools/openapi-generator/issues/22467)
- \[Java] Support JsonNullable in JaxRS-spec
[#&#8203;22412](https://redirect.github.com/openapitools/openapi-generator/issues/22412)
- \[JAVA]\[native] Add support for UnaryInterceptors
[#&#8203;22381](https://redirect.github.com/openapitools/openapi-generator/issues/22381)
- Add support for custom tls server names.
[#&#8203;22372](https://redirect.github.com/openapitools/openapi-generator/issues/22372)
- \[JAVA] \[NATIVE] Add gzip capability
[#&#8203;22358](https://redirect.github.com/openapitools/openapi-generator/issues/22358)
- \[Java] Use Fully Qualified Name for java.util.Locale in Generated
Classes
[#&#8203;22342](https://redirect.github.com/openapitools/openapi-generator/issues/22342)
- \[JAXRS] Partial revert changing path generation if interface, fixes
[#&#8203;22279](https://redirect.github.com/openapitools/openapi-generator/issues/22279)
[#&#8203;22316](https://redirect.github.com/openapitools/openapi-generator/issues/22316)
- \[JAVA jaxrs-spec gen] add option for generating swagger V3
annotations
[#&#8203;22300](https://redirect.github.com/openapitools/openapi-generator/issues/22300)
- \[REQ-22001] Add MCP server support to apiService.mustache
[#&#8203;22197](https://redirect.github.com/openapitools/openapi-generator/issues/22197)

#### Kotlin

- fix(kotlin): add JsonCreator/JsonValue to Jackson enums
[#&#8203;22535](https://redirect.github.com/openapitools/openapi-generator/issues/22535)
- \[kotlin]\[client] Deprecate jvm-volley support
[#&#8203;22521](https://redirect.github.com/openapitools/openapi-generator/issues/22521)
- \[kotlin] fix query parameter encoding
[#&#8203;22512](https://redirect.github.com/openapitools/openapi-generator/issues/22512)
- \[kotlin-client] Vert.x: Fix enum class name template for default
operation parameters
[#&#8203;22504](https://redirect.github.com/openapitools/openapi-generator/issues/22504)
- \[kotlin] Make API classes open (non-final) unless nonPublicApi is
used
[#&#8203;22461](https://redirect.github.com/openapitools/openapi-generator/issues/22461)
- \[kotlin-spring]\[server] Feat: Return from controllers without
ResponseEntity wrapper
[#&#8203;22377](https://redirect.github.com/openapitools/openapi-generator/issues/22377)
- Add support for oneOf with discriminator when using
kotlinx.serialization
[#&#8203;22373](https://redirect.github.com/openapitools/openapi-generator/issues/22373)
- Fix Kotlin codegen for enum with int items (issue
[#&#8203;15204](https://redirect.github.com/openapitools/openapi-generator/issues/15204))
[#&#8203;22324](https://redirect.github.com/openapitools/openapi-generator/issues/22324)
- \[kotlin-spring]\[server] Feat: Add Spring Declarative HTTP Interface
support for easy client instantiation
[#&#8203;22302](https://redirect.github.com/openapitools/openapi-generator/issues/22302)

#### Nim

- \[nim] Nim Generator Fixes
[#&#8203;22385](https://redirect.github.com/openapitools/openapi-generator/issues/22385)

#### PHP

- \[php]\[php-nextgen] Cleanup api authentication code when using api
keys in cookies or supporting multiple authentication methods
[#&#8203;22433](https://redirect.github.com/openapitools/openapi-generator/issues/22433)
- \[php]\[php-nextgen] fix return type if empty and non-empty responses
are mixed
[#&#8203;22322](https://redirect.github.com/openapitools/openapi-generator/issues/22322)
- \[php]\[php-nextgen] fix array enum query parameters
[#&#8203;22320](https://redirect.github.com/openapitools/openapi-generator/issues/22320)
- \[php] Fix PHP generator validation for nullable required properties
[#&#8203;22292](https://redirect.github.com/openapitools/openapi-generator/issues/22292)

#### ProtoBuf

- \[Protobuf] Add isEnumSchema check in generateNestedSchema
[#&#8203;22384](https://redirect.github.com/openapitools/openapi-generator/issues/22384)

#### Python

- python-fastapi: avoid log message in constructor
[#&#8203;22522](https://redirect.github.com/openapitools/openapi-generator/issues/22522)
- Make python code compatible with urllib3 v2.6.0+
[#&#8203;22520](https://redirect.github.com/openapitools/openapi-generator/issues/22520)
- fix: use httpx in generated configuration.py
[#&#8203;22418](https://redirect.github.com/openapitools/openapi-generator/issues/22418)
- \[python] Fix pyproject (poetry 2.x) for httpx
[#&#8203;22289](https://redirect.github.com/openapitools/openapi-generator/issues/22289)

#### Ruby

- \[Ruby] Fixes anyOf Support in Responses
[#&#8203;22392](https://redirect.github.com/openapitools/openapi-generator/issues/22392)

#### Rust

- \[rust-server] feat: Add serde\_validate support
[#&#8203;22553](https://redirect.github.com/openapitools/openapi-generator/issues/22553)
- Update rust-server Cargo.toml to fix client feature compile
[#&#8203;22511](https://redirect.github.com/openapitools/openapi-generator/issues/22511)
- fix: Rust-server bytes response fixed to not attempt string conversion
[#&#8203;22471](https://redirect.github.com/openapitools/openapi-generator/issues/22471)
- \[Rust-Axum] FIX: do not generate Partial Ord/Ord for Any type
[#&#8203;22469](https://redirect.github.com/openapitools/openapi-generator/issues/22469)
- \[Rust] Implement support for multipart file uploads for reqwest-async
and reqwest-trait
[#&#8203;22454](https://redirect.github.com/openapitools/openapi-generator/issues/22454)
- Ensure rust-server compiles with no-default-features
[#&#8203;22445](https://redirect.github.com/openapitools/openapi-generator/issues/22445)
- Add support for trait mocking in rust-server generator
[#&#8203;22332](https://redirect.github.com/openapitools/openapi-generator/issues/22332)
- Fixups for rust-server hyper1 support
[#&#8203;22321](https://redirect.github.com/openapitools/openapi-generator/issues/22321)
- \[Rust-Axum] Fix: incorrect regex pattern validation
[#&#8203;22277](https://redirect.github.com/openapitools/openapi-generator/issues/22277)

#### Scala

- Fixed scala-sttp4-jsoniter compilation error: replace .getRight with
.orFail
[#&#8203;22536](https://redirect.github.com/openapitools/openapi-generator/issues/22536)

#### TypeScript

- \[typescript-fetch]: fix logic when stringEnums is explicitly set to
false
[#&#8203;22466](https://redirect.github.com/openapitools/openapi-generator/issues/22466)
- Typescript-Angular: Fix several query parameters serialization issues
[#&#8203;22459](https://redirect.github.com/openapitools/openapi-generator/issues/22459)
- \[typescript-rxjs] Feat: Add
[@&#8203;deprecated](https://redirect.github.com/deprecated) JSDoc tag
to API operations
[#&#8203;22419](https://redirect.github.com/openapitools/openapi-generator/issues/22419)
- \[typescript-nestjs-server] Fix
[#&#8203;21842](https://redirect.github.com/openapitools/openapi-generator/issues/21842)
by updating api.module.mustache
[#&#8203;22403](https://redirect.github.com/openapitools/openapi-generator/issues/22403)
- \[typescript-node] Fixes generation when parent contains TypeScript
primitive
[#&#8203;22401](https://redirect.github.com/openapitools/openapi-generator/issues/22401)
- \[typescript] replace headers with same case-insensitive key to match
http spec
[#&#8203;22393](https://redirect.github.com/openapitools/openapi-generator/issues/22393)
- \[typescript-axios] add support for accept headers
[#&#8203;22318](https://redirect.github.com/openapitools/openapi-generator/issues/22318)
- fix: Format Date/DateTime Query Parameters in exploded, non-container
Parameter
[#&#8203;22268](https://redirect.github.com/openapitools/openapi-generator/issues/22268)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/line/line-bot-sdk-go).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi41OS4wIiwidXBkYXRlZEluVmVyIjoiNDIuNTkuMCIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6WyJkZXBlbmRlbmN5IHVwZ3JhZGUiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>